//! KeePass key derivation: composite key → KDF → final key.
//!
//! Chain (matches KeePass 2.x / KeePassDX):
//! 1. component keys: password = SHA-256(password UTF-8), keyfile = decoded
//!    32-byte key, hardware key = SHA-256(challenge response).
//! 2. composite key = SHA-256(concat of the 32-byte component keys).
//! 3. transformed key = KDF(composite key) — see `crate::kdf`.
//! 4. final key = SHA-256(master_seed || transformed key).
//! 5. hmac key (KDBX 4.x block auth) = SHA-512(master_seed || transformed || 0x01).

use sha2::{Digest, Sha256, Sha512};

/// SHA-256 of a password's UTF-8 bytes (the password component key).
pub fn password_key(password: &[u8]) -> [u8; 32] {
    Sha256::digest(password).into()
}

/// SHA-256 of the concatenation of the 32-byte component keys.
pub fn composite_key(parts: &[&[u8]]) -> [u8; 32] {
    let mut h = Sha256::new();
    for p in parts {
        h.update(p);
    }
    h.finalize().into()
}

/// Final cipher key: SHA-256(master_seed || transformed_key).
pub fn final_key(master_seed: &[u8; 32], transformed_key: &[u8; 32]) -> [u8; 32] {
    let mut h = Sha256::new();
    h.update(master_seed);
    h.update(transformed_key);
    h.finalize().into()
}

/// KDBX 4.x block-authentication key: SHA-512(master_seed || transformed || 0x01).
pub fn hmac_key(master_seed: &[u8; 32], transformed_key: &[u8; 32]) -> [u8; 64] {
    let mut h = Sha512::new();
    h.update(master_seed);
    h.update(transformed_key);
    h.update([0x01]);
    h.finalize().into()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::encoding::hex;

    // Vectors generated by an independent Python (hashlib) reference.
    #[test]
    fn composite_key_python() {
        let pw = password_key(b"password");
        let kf = password_key(b"keyfile"); // keyfile decoded via SHA-256 fallback
        let composite = composite_key(&[&pw, &kf]);
        assert_eq!(
            hex::encode(&composite),
            "50b1bfdf69281bc9e9b66d5fc1722e21ec4a1fdd2769857dbb38082f7df7251b"
        );
    }

    #[test]
    fn final_and_hmac_key_python() {
        let mut master_seed = [0u8; 32];
        master_seed.copy_from_slice(&(0u8..32).collect::<Vec<_>>());
        let mut transformed = [0u8; 32];
        transformed.copy_from_slice(&(32u8..64).collect::<Vec<_>>());

        assert_eq!(
            hex::encode(&final_key(&master_seed, &transformed)),
            "fdeab9acf3710362bd2658cdc9a29e8f9c757fcf9811603a8c447cd1d9151108"
        );
        assert_eq!(
            hex::encode(&hmac_key(&master_seed, &transformed)),
            "f09af394435628155b2d8ba7af6236610e63c26d6595f5bc508d3e1f2328dd70\
             40c6ce1001efc85f9e7ef54e83df08e2c448fcc47dfd768d7f130de6666c37c3"
        );
    }
}
