//! KDBX 4.x HMAC-authenticated block stream.
//!
//! Layout: for each block — 32-byte HMAC-SHA256, 4-byte size (u32 LE), data.
//! The HMAC key per block is SHA-512(block_index_le64 || hmac_key); the HMAC
//! covers block_index_le64 || size_le32 || data. A zero-size block terminates.

use hmac::{Hmac, Mac};
use sha2::{Digest, Sha256, Sha512};
use subtle::ConstantTimeEq;

use crate::error::{Error, Result};

const DEFAULT_BLOCK_SIZE: usize = 1024 * 1024;

type HmacSha256 = Hmac<Sha256>;

/// Per-block HMAC key: SHA-512(block_index_le64 || hmac_key).
pub fn block_key(block_index: u64, hmac_key: &[u8; 64]) -> [u8; 64] {
    let mut h = Sha512::new();
    h.update(block_index.to_le_bytes());
    h.update(hmac_key);
    h.finalize().into()
}

/// Encodes data into an HMAC-block stream (including the terminating block).
pub fn encode(data: &[u8], hmac_key: &[u8; 64], block_size: usize) -> Vec<u8> {
    let bs = if block_size == 0 {
        DEFAULT_BLOCK_SIZE
    } else {
        block_size
    };
    let mut out = Vec::new();
    let mut index = 0u64;
    if data.is_empty() {
        write_block(&mut out, index, &[], hmac_key);
    } else {
        for chunk in data.chunks(bs) {
            write_block(&mut out, index, chunk, hmac_key);
            index += 1;
        }
        write_block(&mut out, index, &[], hmac_key);
    }
    out
}

/// Decodes an HMAC-block stream, verifying each block's HMAC.
pub fn decode(data: &[u8], hmac_key: &[u8; 64]) -> Result<Vec<u8>> {
    let mut out = Vec::new();
    let mut pos = 0usize;
    let mut index = 0u64;

    loop {
        let stored = read_bytes(data, &mut pos, 32)?;
        let size = read_u32(data, &mut pos)? as usize;
        let block = read_bytes(data, &mut pos, size)?;

        let key = block_key(index, hmac_key);
        let mut mac = HmacSha256::new_from_slice(&key).map_err(|_| Error::InvalidSecret)?;
        mac.update(&index.to_le_bytes());
        mac.update(&(size as u32).to_le_bytes());
        mac.update(block);
        let computed = mac.finalize().into_bytes();
        // Constant-time comparison: the block key derives from the secret
        // composite key, so a short-circuiting `!=` would be a (very local)
        // timing oracle on MAC validity.
        if !bool::from(computed.as_slice().ct_eq(stored)) {
            // The block key derives from the master key; a verification
            // failure means the password/key does not match the data.
            return Err(Error::WrongPassword);
        }

        index += 1;
        if size == 0 {
            break;
        }
        out.extend_from_slice(block);
    }
    Ok(out)
}

fn write_block(out: &mut Vec<u8>, index: u64, data: &[u8], hmac_key: &[u8; 64]) {
    let key = block_key(index, hmac_key);
    let size = (data.len() as u32).to_le_bytes();
    let mut mac = HmacSha256::new_from_slice(&key).expect("HMAC key is always valid");
    mac.update(&index.to_le_bytes());
    mac.update(&size);
    mac.update(data);
    out.extend_from_slice(&mac.finalize().into_bytes());
    out.extend_from_slice(&size);
    out.extend_from_slice(data);
}

fn read_u32(data: &[u8], pos: &mut usize) -> Result<u32> {
    let b = read_bytes(data, pos, 4)?;
    Ok(u32::from_le_bytes([b[0], b[1], b[2], b[3]]))
}

fn read_bytes<'a>(data: &'a [u8], pos: &mut usize, len: usize) -> Result<&'a [u8]> {
    // saturating_sub instead of `pos + len`: a hostile u32 block size must
    // never overflow the bounds check.
    if len > data.len().saturating_sub(*pos) {
        return Err(Error::Format("truncated hmac block stream".to_string()));
    }
    let s = &data[*pos..*pos + len];
    *pos += len;
    Ok(s)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::encoding::hex;

    #[test]
    fn roundtrip() {
        let hmac_key = [0x55u8; 64];
        for len in [0usize, 1, 100, 1024, 1024 * 1024 + 7] {
            let data: Vec<u8> = (0..len).map(|i| (i % 251) as u8).collect();
            let enc = encode(&data, &hmac_key, 1024);
            assert_eq!(decode(&enc, &hmac_key).unwrap(), data, "len={len}");
        }
    }

    #[test]
    fn golden_vector() {
        // Generated by independent Python (hashlib + hmac) reference.
        let hmac_key: Vec<u8> = (0u8..64).collect();
        let key: [u8; 64] = hmac_key.try_into().unwrap();
        let data = b"hello hmac block";
        let expected = hex::decode(
            "55e6937edd77df9516948726ef09c0d5d94060c7264c58620c497c6e7b611cc9\
             10000000\
             68656c6c6f20686d616320626c6f636b\
             8ba6dea07ed761e19b34be2027ec6bed92620b9459b552cb4a63f54bdfebc5e6\
             00000000",
        )
        .unwrap();

        assert_eq!(encode(data, &key, 1024 * 1024), expected);
        assert_eq!(decode(&expected, &key).unwrap(), data);
    }

    #[test]
    fn tamper_detected() {
        let hmac_key = [0x11u8; 64];
        let mut enc = encode(b"some data", &hmac_key, 16);
        let n = enc.len();
        enc[n - 5] ^= 0xFF; // flip a data byte
        assert!(decode(&enc, &hmac_key).is_err());
    }
}
