//! Known-answer tests for the de-facto variants (Steam/MOTP/Yandex).
//!
//! Expected values were generated by an independent Python implementation of
//! the publicly documented algorithms (see the values below).

use onepass_engine::encoding::hex;
use onepass_engine::otp::{motp, steam, yandex, OtpKind, OtpParams};
use onepass_engine::uri;

#[test]
fn steam_vectors() {
    let secret = b"12345678901234567890";
    let expected = [
        (59u64, "PV9M4"),
        (1_111_111_109, "PY4YB"),
        (1_234_567_890, "VHHQY"),
        (2_000_000_000, "9N776"),
    ];
    for (t, code) in expected {
        assert_eq!(steam::steam(secret, 30, t).unwrap(), code, "t={t}");
    }
}

#[test]
fn motp_vectors() {
    let cases = [
        ("1234567890abcdef", "1234", 1_700_000_000u64, "660af9"),
        ("00112233445566778899aabbccddeeff", "0000", 0, "8e71ac"),
    ];
    for (secret_hex, pin, t, expected) in cases {
        let secret = hex::decode(secret_hex).unwrap();
        assert_eq!(motp::motp(&secret, pin, 10, 6, t).unwrap(), expected);
    }
}

#[test]
fn yandex_vectors() {
    let cases = [
        ("00112233445566778899aabbccddeeff", "1234", 1_700_000_000u64, "jjeghxtd"),
        ("00112233445566778899aabbccddeeff", "0000", 0, "unnyoebf"),
    ];
    for (secret_hex, pin, t, expected) in cases {
        let secret = hex::decode(secret_hex).unwrap();
        assert_eq!(yandex::yandex(&secret, pin, 30, 8, t).unwrap(), expected);
    }
}

#[test]
fn steam_uri_roundtrip_and_generate() {
    let uri_str = "otpauth://steam/player:steamuser?secret=JBSWY3DPEHPK3PXP";
    let p = uri::parse(uri_str).unwrap();
    assert_eq!(p.kind, OtpKind::Steam);
    // deterministic: same t -> same code
    assert_eq!(p.generate(59).unwrap(), p.generate(59).unwrap());
    let rebuilt = uri::build(&p).unwrap();
    let p2 = uri::parse(&rebuilt).unwrap();
    assert_eq!(p.secret, p2.secret);
    assert_eq!(p2.digits, 5);
}

#[test]
fn yandex_uri_roundtrip_and_generate() {
    let secret = hex::decode("00112233445566778899aabbccddeeff").unwrap();
    let p = OtpParams {
        kind: OtpKind::Yandex,
        secret,
        pin: Some("1234".to_string()),
        issuer: "yandex".to_string(),
        account: "user".to_string(),
        ..Default::default()
    };
    let uri_str = uri::build(&p).unwrap();
    let p2 = uri::parse(&uri_str).unwrap();
    assert_eq!(p2.generate(1_700_000_000).unwrap(), "jjeghxtd");
}
