// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Full entry for the detail view. Protected field values are blanked;
/// use `reveal_field` to fetch them on demand.
class EntryDetail {
  final String uuid;
  final int iconId;
  final PlatformInt64 creation;
  final PlatformInt64 lastModification;
  final List<FieldDto> fields;

  const EntryDetail({
    required this.uuid,
    required this.iconId,
    required this.creation,
    required this.lastModification,
    required this.fields,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      iconId.hashCode ^
      creation.hashCode ^
      lastModification.hashCode ^
      fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryDetail &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          iconId == other.iconId &&
          creation == other.creation &&
          lastModification == other.lastModification &&
          fields == other.fields;
}

/// Compact entry row for list views.
class EntryDto {
  /// 16-byte entry uuid, hex encoded.
  final String uuid;
  final int iconId;
  final String title;
  final String username;
  final String url;
  final String notes;
  final bool hasOtp;

  /// .NET epoch seconds (0 = unknown).
  final PlatformInt64 creation;

  /// .NET epoch seconds (0 = unknown).
  final PlatformInt64 lastModification;

  const EntryDto({
    required this.uuid,
    required this.iconId,
    required this.title,
    required this.username,
    required this.url,
    required this.notes,
    required this.hasOtp,
    required this.creation,
    required this.lastModification,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      iconId.hashCode ^
      title.hashCode ^
      username.hashCode ^
      url.hashCode ^
      notes.hashCode ^
      hasOtp.hashCode ^
      creation.hashCode ^
      lastModification.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryDto &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          iconId == other.iconId &&
          title == other.title &&
          username == other.username &&
          url == other.url &&
          notes == other.notes &&
          hasOtp == other.hasOtp &&
          creation == other.creation &&
          lastModification == other.lastModification;
}

/// A single entry field as stored.
class FieldDto {
  final String key;
  final String value;
  final bool protected;

  const FieldDto({
    required this.key,
    required this.value,
    required this.protected,
  });

  @override
  int get hashCode => key.hashCode ^ value.hashCode ^ protected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FieldDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value &&
          protected == other.protected;
}

/// Fields of a 2FA entry.
class OtpEntryInput {
  final String issuer;
  final String account;

  /// Base32 secret, or a full `otpauth://` URI (auto-detected).
  final String secretOrUri;

  /// totp | hotp | steam | motp | yandex (ignored for URI input)
  final String kind;

  /// SHA1 | SHA256 | SHA512 (ignored for URI input)
  final String algorithm;
  final int digits;
  final BigInt period;
  final BigInt counter;

  /// PIN for motp/yandex (empty = none)
  final String pin;

  const OtpEntryInput({
    required this.issuer,
    required this.account,
    required this.secretOrUri,
    required this.kind,
    required this.algorithm,
    required this.digits,
    required this.period,
    required this.counter,
    required this.pin,
  });

  @override
  int get hashCode =>
      issuer.hashCode ^
      account.hashCode ^
      secretOrUri.hashCode ^
      kind.hashCode ^
      algorithm.hashCode ^
      digits.hashCode ^
      period.hashCode ^
      counter.hashCode ^
      pin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OtpEntryInput &&
          runtimeType == other.runtimeType &&
          issuer == other.issuer &&
          account == other.account &&
          secretOrUri == other.secretOrUri &&
          kind == other.kind &&
          algorithm == other.algorithm &&
          digits == other.digits &&
          period == other.period &&
          counter == other.counter &&
          pin == other.pin;
}

/// Parsed OTP configuration of an entry.
class OtpInfoDto {
  /// totp | hotp | steam | motp | yandex
  final String kind;
  final String issuer;
  final String account;

  /// SHA1 | SHA256 | SHA512 | MD5
  final String algorithm;
  final int digits;
  final BigInt period;
  final BigInt counter;
  final bool hasPin;

  const OtpInfoDto({
    required this.kind,
    required this.issuer,
    required this.account,
    required this.algorithm,
    required this.digits,
    required this.period,
    required this.counter,
    required this.hasPin,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      issuer.hashCode ^
      account.hashCode ^
      algorithm.hashCode ^
      digits.hashCode ^
      period.hashCode ^
      counter.hashCode ^
      hasPin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OtpInfoDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          issuer == other.issuer &&
          account == other.account &&
          algorithm == other.algorithm &&
          digits == other.digits &&
          period == other.period &&
          counter == other.counter &&
          hasPin == other.hasPin;
}

/// Fields of a standard password entry.
class PasswordEntryInput {
  final String title;
  final String username;
  final String password;
  final String url;
  final String notes;

  const PasswordEntryInput({
    required this.title,
    required this.username,
    required this.password,
    required this.url,
    required this.notes,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      username.hashCode ^
      password.hashCode ^
      url.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PasswordEntryInput &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          username == other.username &&
          password == other.password &&
          url == other.url &&
          notes == other.notes;
}

/// Password generator policy.
class PasswordPolicyDto {
  final bool upper;
  final bool lower;
  final bool digits;
  final bool symbols;
  final bool excludeAmbiguous;
  final bool requireEachSet;

  const PasswordPolicyDto({
    required this.upper,
    required this.lower,
    required this.digits,
    required this.symbols,
    required this.excludeAmbiguous,
    required this.requireEachSet,
  });

  @override
  int get hashCode =>
      upper.hashCode ^
      lower.hashCode ^
      digits.hashCode ^
      symbols.hashCode ^
      excludeAmbiguous.hashCode ^
      requireEachSet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PasswordPolicyDto &&
          runtimeType == other.runtimeType &&
          upper == other.upper &&
          lower == other.lower &&
          digits == other.digits &&
          symbols == other.symbols &&
          excludeAmbiguous == other.excludeAmbiguous &&
          requireEachSet == other.requireEachSet;
}
