// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`

/// Bridge error: a category plus a human-readable message.
class BridgeError implements FrbException {
  final ErrorKind kind;
  final String message;

  const BridgeError({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

/// Coarse error category the UI can switch on.
enum ErrorKind {
  /// The supplied password does not match the vault.
  wrongPassword,

  /// The vault file is structurally invalid.
  format,

  /// File system failure (read/write).
  io,

  /// Invalid user input (bad secret, bad policy, unknown uuid, ...).
  invalidParameter,

  /// The operation requires an unlocked vault (or conflicts with one).
  sessionState,

  /// Anything else.
  other,
}
