// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Opens (decrypts) the vault file and starts a session.
Future<List<EntryDto>> openVault({
  required String path,
  required List<int> password,
}) =>
    RustLib.instance.api.crateApiVaultOpenVault(path: path, password: password);

/// Imports a picked `.kdbx` file: validates the password against it, then
/// adopts it as the session and writes a fresh copy to `target` on save.
Future<List<EntryDto>> importVaultFile({
  required String path,
  required List<int> password,
  required String target,
}) => RustLib.instance.api.crateApiVaultImportVaultFile(
  path: path,
  password: password,
  target: target,
);

/// Validates a master password against the vault file without opening a
/// session (used when enabling biometric unlock).
Future<bool> checkVaultPassword({
  required String path,
  required List<int> password,
}) => RustLib.instance.api.crateApiVaultCheckVaultPassword(
  path: path,
  password: password,
);

/// Creates a new vault in memory. Call `save_session` to write it to disk.
Future<void> createVault({
  required String path,
  required String name,
  required List<int> password,
}) => RustLib.instance.api.crateApiVaultCreateVault(
  path: path,
  name: name,
  password: password,
);

/// Encrypts and writes the session vault. Returns `false` when clean.
Future<bool> saveSession() => RustLib.instance.api.crateApiVaultSaveSession();

/// Drops the session (password zeroized on the Rust side).
Future<void> lockVault() => RustLib.instance.api.crateApiVaultLockVault();

/// Replaces the master password used for the next save.
Future<void> changeMasterPassword({required List<int> newPassword}) => RustLib
    .instance
    .api
    .crateApiVaultChangeMasterPassword(newPassword: newPassword);

/// Whether a vault session is currently unlocked.
bool isUnlocked() => RustLib.instance.api.crateApiVaultIsUnlocked();

/// Whether the unlocked session has unsaved changes (false when locked).
bool isDirty() => RustLib.instance.api.crateApiVaultIsDirty();

Future<List<EntryDto>> listEntries() =>
    RustLib.instance.api.crateApiVaultListEntries();

/// Full entry for the detail view (protected values blanked).
Future<EntryDetail> entryDetail({required String uuidHex}) =>
    RustLib.instance.api.crateApiVaultEntryDetail(uuidHex: uuidHex);

/// Fetches one field value on demand (e.g. the password).
Future<String> revealField({required String uuidHex, required String key}) =>
    RustLib.instance.api.crateApiVaultRevealField(uuidHex: uuidHex, key: key);

/// Adds a password entry, returning its hex uuid.
Future<String> addPasswordEntry({required PasswordEntryInput input}) =>
    RustLib.instance.api.crateApiVaultAddPasswordEntry(input: input);

/// Adds a 2FA entry, returning its hex uuid.
Future<String> addOtpEntry({required OtpEntryInput input}) =>
    RustLib.instance.api.crateApiVaultAddOtpEntry(input: input);

Future<void> updatePasswordEntry({
  required String uuidHex,
  required PasswordEntryInput input,
}) => RustLib.instance.api.crateApiVaultUpdatePasswordEntry(
  uuidHex: uuidHex,
  input: input,
);

Future<void> updateOtpEntry({
  required String uuidHex,
  required OtpEntryInput input,
}) => RustLib.instance.api.crateApiVaultUpdateOtpEntry(
  uuidHex: uuidHex,
  input: input,
);

/// Removes entries (and any nested ones), returning how many were deleted.
Future<BigInt> deleteEntries({required List<String> uuidHexes}) =>
    RustLib.instance.api.crateApiVaultDeleteEntries(uuidHexes: uuidHexes);

/// Parsed OTP configuration of an entry, if any.
Future<OtpInfoDto?> otpInfo({required String uuidHex}) =>
    RustLib.instance.api.crateApiVaultOtpInfo(uuidHex: uuidHex);

/// Parses an `otpauth://` URI (e.g. a scanned QR payload) into display
/// fields. Cheap and side-effect free.
OtpInfoDto parseOtpauthUri({required String uri}) =>
    RustLib.instance.api.crateApiVaultParseOtpauthUri(uri: uri);

/// Current OTP code at `time_secs` (unix seconds); cheap enough for 1s ticks.
String? otpCode({required String uuidHex, required BigInt timeSecs}) => RustLib
    .instance
    .api
    .crateApiVaultOtpCode(uuidHex: uuidHex, timeSecs: timeSecs);

/// Auto-detects the format (Aegis JSON / Google migration / URI list) and
/// appends the imported entries to the vault root.
Future<List<EntryDto>> importFromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiVaultImportFromBytes(bytes: bytes);

/// Imports a text list of `otpauth://` URIs.
Future<List<EntryDto>> importFromOtpauthText({required String text}) =>
    RustLib.instance.api.crateApiVaultImportFromOtpauthText(text: text);

/// Exports all 2FA entries as an `otpauth://` URI list.
Future<String> exportOtpauthText() =>
    RustLib.instance.api.crateApiVaultExportOtpauthText();

/// Exports all 2FA entries as Aegis JSON.
Future<Uint8List> exportAegis() =>
    RustLib.instance.api.crateApiVaultExportAegis();

String generatePassword({
  required int len,
  required PasswordPolicyDto policy,
}) => RustLib.instance.api.crateApiVaultGeneratePassword(
  len: len,
  policy: policy,
);
